### ISSUE TITLE
Problem with wrapper

### ISSUE THREAD

**Issue by adelval1** [mutationpp/Mutationpp#100]
Hello,

I leave the issue with the coupling stagline/m++ here. When installing the stagline I get:

[ 94%] Linking Fortran executable stagline
Undefined symbols for architecture x86_64:
  "_mpp_get_wall_state_", referenced from:
      ___mod_mutationpp_library_MOD_mutationpp_get_wall_state in mod_Mutationpp_library.F90.o
  "_mpp_set_wall_state_", referenced from:
      ___mod_mutationpp_library_MOD_mutationpp_set_wall_state in mod_Mutationpp_library.F90.o
  "_mpp_wall_production_rates_", referenced from:
      ___mod_mutationpp_library_MOD_mutationpp_get_surface_production_rates in mod_Mutationpp_library.F90.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [stagline] Error 1
make[1]: *** [CMakeFiles/stagline.dir/all] Error 2
make: *** [all] Error 2

I guess it's just a matter of change of names in the new mutation.

Cheers

**Comment by grgbellasvki** [comment]
Hello Anabel,

The functions should be changed inside stagline. Is the problem fixed so that I can close this issue?

**Comment by jbscoggi** [comment]
This seems like a dead issue.  Closing.
