### ISSUE TITLE
CMake Export

### ISSUE THREAD

**Issue by khansson** [mutationpp/Mutationpp#101]
Does a FindMUTATIONPP.cmake already exist or does mutationpp have a cmake export?

https://cmake.org/cmake/help/v3.12/command/export.html

Ideally, cmake should be able to find mutationpp and the associated lib and include directories right from either a Mutationpp_ROOT_DIR or the MPP_DIRECTORY environmental variable.

**Comment by rubendibattista** [comment]
@khansson `mutation++` exports a `mutation++Config.cmake` file since `v1.0.0`. Did you tried it?

**Comment by rubendibattista** [comment]
It's located (as normally) in `<install_dir>/lib/cmake`

**Comment by rubendibattista** [comment]
@khansson No problem. :)

@jbscoggins, can you maybe archive the gitlab repository on VKI servers (maybe editing the `README` and the description there saying that the official repo is here now?) 

It's not the first one trying to apply modern recipes against old codebase.
