### ISSUE TITLE
Type definition bug line 285 of Transport.cpp

### ISSUE THREAD

**Issue by jcschulz** [mutationpp/Mutationpp#115]
The variable `ei` should be a vector of integers, not doubles. See the following snippet:

```    
// Find the elements
Eigen::VectorXi ei(ne);   // Not Eigen::VectorXd ei(ne); 
for (int i = 0; i < ne; ++i)
    ei(i) = m_thermo.speciesIndex(m_thermo.elementName(i));
```

This fixes the compile-time error when using the Intel 2018 compiler.

**Comment by jbscoggi** [comment]
Hi @jcschulz.  Thanks for catching that.  Do you mind just submitting a PR with the update?
