### ISSUE TITLE
Fortran wrapper access to heavyThermalDiffusionRatios

### ISSUE THREAD

**Issue by ChiaraAmato** [mutationpp/Mutationpp#118]
I have implemented the function "heavyThermalDiffusionRatios" in both cwrapper.h and cwrapper.cpp following the function "frozenThermalConductivity". However, when I run a testcase usign N2 and O2, I received that the Thermal diffusion ratios are zero for both species. Furthermore, can you confirm that the "heavyThermalDiffusionRatios" function is evaluating the coefficients for the temperature term in the diffusive velocities for the Stefan-Maxwell equation?

[cwrapper.zip](https://github.com/mutationpp/Mutationpp/files/4356887/cwrapper.zip)

**Comment by rubendibattista** [comment]
Ehi @ChiaraAmato, maybe it would have a better luck if you can provide a Pull Request. So we can maybe comment your modifications directly there. 

Do you think you can do that?

**Comment by ChiaraAmato** [comment]
Yes, I can. I just need to create a branch and then a “pull request”, right? If so, I will do it now.

Thank you so much.
Chiara Amato
Ph.D. Student in Hypersonics, 
Graduate Women Coordinator
Department of Aerospace Engineering
University of Minnesota
National Hypersonic Research Center, Akerman Hall 230
E-mail: amato017@umn.edu <mailto:amato017@umn.edu>
Mobile: (651) 494-8409

**Comment by rubendibattista** [comment]
You need to create a fork, than you'll be able to make a PR. There're plenty of guides online ;)

**Comment by ChiaraAmato** [comment]
I did create a Pull Request. Please, let me know if everything is ok.
Thanks :)

**Comment by jbscoggi** [comment]
Closing since this was fixed in #123
