### ISSUE TITLE
Segmentation fault when using the mppequil to load pure species collision integrals

### ISSUE THREAD

**Issue by gsalaza3** [mutationpp/Mutationpp#120]
I am getting a segmentation fault when trying to use the mppequil utility to load the pure species collision integrals "Omega11" and "Omega22". I have tested it with different mixtures and get the same error:

mppequil -T 300 -P 101325 -s 15,16 O2
  "Omega11_O[m^2]"  "Omega11_O2[m^2]"  "Omega22_O[m^2]"  "Omega22_O2[m^2]"
Segmentation fault

Thanks!

**Comment by rubendibattista** [comment]
Hi @gsalaza3, can you please provide the **complete** steps you took to compile the software? 
Could you also provide more information on the platform you're working with? `uname -a` on the terminal.

**Comment by gsalaza3** [comment]
Hey @rubendibattista . I cloned it this morning just to make sure I was using the latest, but I followed the steps on the installation page (https://github.com/mutationpp/Mutationpp/blob/master/docs/installation.md#top) : 

cd mutationpp
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX:PATH=/beegfs/users/gsalazar/codes/mutationpp/install ..
make -j 4 install

Here's the output of that "uname" command: 
Linux   3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 10:44:42 CDT 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rubendibattista** [comment]
Ok, can you please upload the `strace.log` file produced by the following command: 
```
strace -o strace.log mppequil -T 300 -P 101325 -s 15,16 O2
```

and also the output of the following commands: 

```
echo $PATH
echo $LD_LIBRARY_PATH
```

**Comment by jbscoggi** [comment]
Hi @gsalaza3, I have fixed this bug in #122.  It was just a simple mistake in mppequil.  Assuming all the tests pass, we can merge the PR and this should be closed.  

@rubendibattista, since you were handling this, do you mind to do the code review (should be very quick)?

**Comment by gsalaza3** [comment]
Thanks @rubendibattista and @jbscoggi  for the quick help with this one!

**Comment by jbscoggi** [comment]
Hi @gsalaza3, the fix is now merged.  It should work if you pull the latest version.
