### ISSUE TITLE
Average Heavy Collision Frequency

### ISSUE THREAD

**Issue by ggange** [mutationpp/Mutationpp#127]
Hello!
I was going through the Transport.cpp file in src/transport and found this expression for the average heavy collision frequency:
`double Transport::averageHeavyCollisionFreq()
{
  return meanFreePath()/averageHeavyThermalSpeed();
}`
Should it be the inverse? If yes do you know if it affects other functions?
Thank you!

**Comment by grgbellasvki** [comment]
Thank you for the comment. I think you are right about the formula and should be fixed. This function is only used in "mppequil" and does not affect the calculation of other quantities.

**Comment by ggange** [comment]
Perfect! thank you!

**Comment by jbscoggi** [comment]
This was fixed in #158, closing.
