### ISSUE TITLE
No return on the prompt command

### ISSUE THREAD

**Issue by cesarpanpan** [mutationpp/Mutationpp#128]
Hello,

I need to use mutationpp on windows and so I use Cygwin. I did install the thirdparties and mutationpp and there is no error in the log. 

The problem is when I execute mppequil with the example command, I have no result given. At first, I wasn't worried but my program using it can't get any result from it also and so give errors. 

I am really clueless on this problem, as anyone already encounter this issue? 

thanks.

**Comment by rubendibattista** [comment]
Hello @cesarpanpan, could you please the same information I asked [here](https://github.com/mutationpp/Mutationpp/issues/124#issuecomment-617760923) in order to try to give a hand? :)

**Comment by cesarpanpan** [comment]
Hello,

thanks for helping me, it is really nice of you.

First, the steps to build mutationpp : -I installed the third parties Eigen
and catch by doing a build folder in /Mutationpp-Master/thirdparty/eigen
or  /Mutationpp-Master/thirdparty/catch and installing them with default
option by using the cmake in their respecting folders.
-Then I went to the /Mutationpp-Master folder I have and use those command
lines as described by the installation instructions file :
         mkdir build
         cd build
         cmake -DCMAKE_INSTALL_PREFIX:PATH=$(realpath ../install) ..
         make -j 1 install
I checked, I have /lib and not /lib64
-The installation seems to went well
-I went to /Mutationpp-Master/install/bin where mppequil.exe is, if I type
: ./mppequil.exe -h, it does print the help of this application and
provides the example : ./mppequil -T 300:100:15000 -P 101325 -m 1-3,8 air11

I put the cmake output  in linked file.

I am unable to give you the required command for the other machine because
I do not have access to it. Furthermore, I'm sorry but I can't give you the
CMakeList of my program for confidentiality reason.

uname -a
CYGWIN_NT-10.0 LAPTOP-DSEON50Q 3.1.4(0.340/5/3) 2020-02-19 08:49 x86_64
Cygwin

$ env
USERDOMAIN=LAPTOP-DSEON50Q
OS=Windows_NT
COMMONPROGRAMFILES=C:\Program Files\Common Files
MSMPI_INC=C:\Program Files\Microsoft HPC Pack 2008 R2\Inc\
PROCESSOR_LEVEL=6
PSModulePath=C:\Program
Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
CommonProgramW6432=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
LANG=fr_FR.UTF-8
TZ=Europe/Paris
platformcode=KV
HOSTNAME=LAPTOP-DSEON50Q
PUBLIC=C:\Users\Public
OLDPWD=/cygdrive/d/pasracine/Mutationpp-master
OnlineServices=Online Services
USERNAME=Florent
LOGONSERVER=\\LAPTOP-DSEON50Q
PROCESSOR_ARCHITECTURE=AMD64
LOCALAPPDATA=C:\Users\Florent\AppData\Local
ADSK_CLM_WPAD_PROXY_CHECK=FALSE
COMPUTERNAME=LAPTOP-DSEON50Q
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
USER=Florent
!::=::\
SYSTEMDRIVE=C:
VISIT_MPIEXEC=C:\Program Files\Microsoft HPC Pack 2008 R2\Bin\mpiexec.exe
USERPROFILE=C:\Users\Florent
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
GNUTERM=windows
SYSTEMROOT=C:\WINDOWS
USERDOMAIN_ROAMINGPROFILE=LAPTOP-DSEON50Q
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
PWD=/cygdrive/d/pasracine/Mutationpp-master/build
HOME=/home/Florent
TMP=/tmp
VISITLOC=D:\Visit\LLNL\VisIt 3.1.1
OneDrive=C:\Users\Florent\OneDrive
PROCESSOR_REVISION=9e09
FPS_BROWSER_USER_PROFILE_STRING=Default
PROFILEREAD=true
LIB=C:\Program Files
(x86)\IntelSWTools\compilers_and_libraries_2019\windows\compiler\lib\intel64
MSMPI_LIB32=C:\Program Files\Microsoft HPC Pack 2008 R2\Lib\i386\
NUMBER_OF_PROCESSORS=4
ProgramW6432=C:\Program Files
INTEL_LICENSE_FILE=C:\Program Files (x86)\Common Files\Intel\Licenses
MSMPI_LIB64=C:\Program Files\Microsoft HPC Pack 2008 R2\Lib\amd64\
COMSPEC=C:\WINDOWS\system32\cmd.exe
APPDATA=C:\Users\Florent\AppData\Roaming
SHELL=/bin/bash
TERM=xterm
WINDIR=C:\WINDOWS
ProgramData=C:\ProgramData
SHLVL=1
MINTTY_SHORTCUT=/cygdrive/c/Users/Public/Desktop/Cygwin64 Terminal.lnk
PRINTER=Canon iP110 series WS
PROGRAMFILES=C:\Program Files
ALLUSERSPROFILE=C:\ProgramData
TEMP=/tmp
ifort=C:\Program Files
(x86)\IntelSWTools\compilers_and_libraries_2019\windows\bin\intel64\ifort.bat
DriverData=C:\Windows\System32\Drivers\DriverData
SESSIONNAME=Console
RegionCode=EMEA
ProgramFiles(x86)=C:\Program Files (x86)
PATH=/usr/local/bin:/usr/bin:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS:/cygdrive/c/Program
Files (x86)/Common
Files/Oracle/Java/javapath:/cygdrive/c/SIMULIA/Commands:/cygdrive/c/Program
Files (x86)/Common Files/Intel/Shared
Libraries/redist/intel64_win/mpirt:/cygdrive/c/Program Files (x86)/Common
Files/Intel/Shared Libraries/redist/ia32_win/mpirt:/cygdrive/c/Program
Files (x86)/Common Files/Intel/Shared
Libraries/redist/intel64_win/compiler:/cygdrive/c/Program Files
(x86)/Common Files/Intel/Shared
Libraries/redist/ia32_win/compiler:/cygdrive/c/Program Files/Microsoft HPC
Pack 2008 R2/Bin:/cygdrive/c/Program Files (x86)/Intel/iCLS
Client:/cygdrive/c/Program Files/Intel/iCLS
Client:/cygdrive/c/windows/system32:/cygdrive/c/windows:/cygdrive/c/windows/System32/Wbem:/cygdrive/c/windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program
Files (x86)/Intel/Intel(R) Management Engine
Components/DAL:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine
Components/DAL:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management
Engine Components/IPT:/cygdrive/c/Program Files/Intel/Intel(R) Management
Engine Components/IPT:/cygdrive/c/Program Files (x86)/NVIDIA
Corporation/PhysX/Common:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/WINDOWS/System32/OpenSSH:/cygdrive/c/Program
Files/Intel/WiFi/bin:/cygdrive/c/Program Files/Common
Files/Intel/WirelessCommon:/cygdrive/c/Program Files (x86)/Windows
Kits/10/Windows Performance Toolkit:/cygdrive/c/Program
Files/gnuplot/bin:/cygdrive/d/Visit/LLNL/VisIt
3.1.1:/cygdrive/c/Users/Florent/AppData/Local/Microsoft/WindowsApps:/cygdrive/c/Program
Files
(x86)/IntelSWTools/compilers_and_libraries_2019/windows/bin:/cygdrive/c/Program
Files
(x86)/IntelSWTools/compilers_and_libraries_2019/windows/bin/intel64:/cygdrive/c/Program
Files (x86)/Microsoft Visual Studio/2017/Community/VC/Auxiliary/Build
PS1=\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$
HOMEDRIVE=C:
INFOPATH=/usr/local/info:/usr/share/info:/usr/info
HOMEPATH=\Users\Florent
ORIGINAL_PATH=/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS:/cygdrive/c/Program
Files (x86)/Common
Files/Oracle/Java/javapath:/cygdrive/c/SIMULIA/Commands:/cygdrive/c/Program
Files (x86)/Common Files/Intel/Shared
Libraries/redist/intel64_win/mpirt:/cygdrive/c/Program Files (x86)/Common
Files/Intel/Shared Libraries/redist/ia32_win/mpirt:/cygdrive/c/Program
Files (x86)/Common Files/Intel/Shared
Libraries/redist/intel64_win/compiler:/cygdrive/c/Program Files
(x86)/Common Files/Intel/Shared
Libraries/redist/ia32_win/compiler:/cygdrive/c/Program Files/Microsoft HPC
Pack 2008 R2/Bin:/cygdrive/c/Program Files (x86)/Intel/iCLS
Client:/cygdrive/c/Program Files/Intel/iCLS
Client:/cygdrive/c/windows/system32:/cygdrive/c/windows:/cygdrive/c/windows/System32/Wbem:/cygdrive/c/windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program
Files (x86)/Intel/Intel(R) Management Engine
Components/DAL:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine
Components/DAL:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management
Engine Components/IPT:/cygdrive/c/Program Files/Intel/Intel(R) Management
Engine Components/IPT:/cygdrive/c/Program Files (x86)/NVIDIA
Corporation/PhysX/Common:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/WINDOWS/System32/OpenSSH:/cygdrive/c/Program
Files/Intel/WiFi/bin:/cygdrive/c/Program Files/Common
Files/Intel/WirelessCommon:/cygdrive/c/Program Files (x86)/Windows
Kits/10/Windows Performance Toolkit:/cygdrive/c/Program
Files/gnuplot/bin:/cygdrive/d/Visit/LLNL/VisIt
3.1.1:/cygdrive/c/Users/Florent/AppData/Local/Microsoft/WindowsApps:/cygdrive/c/Program
Files
(x86)/IntelSWTools/compilers_and_libraries_2019/windows/bin:/cygdrive/c/Program
Files
(x86)/IntelSWTools/compilers_and_libraries_2019/windows/bin/intel64:/cygdrive/c/Program
Files (x86)/Microsoft Visual Studio/2017/Community/VC/Auxiliary/Build
EXECIGNORE=*.dll
OMP_NUM_THREADS=4
_=/usr/bin/env

Le ven. 29 mai 2020 à 16:43, Ruben Di Battista <notifications@github.com> a
écrit :

**Comment by rubendibattista** [comment]
Ehi, I'll try to see what I can do. You're using Cygwin. Did you try to use [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) instead? It works pretty well nowadays. 

Can you post the content of `strace.out` and `strace.err` files after running this command?
```
strace -o strace.out ./mppequil -T 300:100:15000 -P 101325 -m 1-3,8 air11 2>strace.err
```

**Comment by cesarpanpan** [comment]
Ok, I will install wsl and see how it goes.

Le mar. 2 juin 2020 à 11:32, Ruben Di Battista <notifications@github.com> a
écrit :

**Comment by rubendibattista** [comment]
Any success @cesarpanpan?

**Comment by cesarpanpan** [comment]
Hi Ruben,

Yes, mutation ++ is working on my computer. Instaling WSL was the good
idea.

Thank you

Sincerely yours,
Florent
