### ISSUE TITLE
I can not link mutation++ with SU2. but SU2 can run really well.

### ISSUE THREAD

**Issue by tu-97** [mutationpp/Mutationpp#161]
**Cmake Version:3.10.2

sudo ./meson.py build  -Denable-mpp=true  --prefix=/usr/local/SU2

![Snipaste_2021-03-31_22-49-11](https://user-images.githubusercontent.com/74906968/113164278-8da18800-9273-11eb-98c5-1325032bcbe7.png)

**Comment by tu-97** [comment]
WARNING: CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.

**Comment by tu-97** [comment]
when I copy the executable program  "ninja"  at   /home/usersname/SU2/external/ninja/ninja    to  /usr/local/bin/ninja
then run  sudo ./meson.py build -Denable-mpp=true --prefix=/usr/local/SU2
problem solved!!

**Comment by rubendibattista** [comment]
Just FYI, that's absolutely a terrible idea to copy something manually inside `/usr/local/bin`. You need to install `ninja` using your package manager or install it locally into your own and let `Cmake` know the correct path.
