### ISSUE TITLE
CMake Fortran compiler flags not set properly

### ISSUE THREAD

**Issue by mgoodson-cvd** [mutationpp/Mutationpp#190]
The CMake Fortran compiler flags defined [here](https://github.com/mutationpp/Mutationpp/blob/c9a924fde43216e0777a918dc5042eaa18ae98b5/CMakeLists.txt#L153-163) are not set properly because the calls to `set` are missing the `CACHE` and `FORCE` attributes.  The `CMAKE_<LANG>_FLAGS*` are defined by CMake and are cached, so we need the `CACHE` flag when setting them explicitly to override the defaults. We also need the `FORCE` attribute to override the CMake default values for these variables.

**Comment by rubendibattista** [comment]
Are you sure about this? It's a new behavior? I never had to force cache compiler flags ever before... And I tested the Fortran interface not so long ago and it was working as expected.

**Comment by mgoodson-cvd** [comment]
It will still work fine as-is, but the Fortran compiler flags will be set to the CMake defaults rather than what you're setting them to be. Check your `CMakeCache.txt` after running CMake and compare the `CMAKE_Fortran_FLAGS*` in there against what is being specified [here](https://github.com/mutationpp/Mutationpp/blob/c9a924fde43216e0777a918dc5042eaa18ae98b5/CMakeLists.txt#L153-163) in CMakeLists.txt.

**Comment by mgoodson-cvd** [comment]
Also, it's worth pointing out that the `CMAKE_CXX_Profile` are force cached [in that same file](https://github.com/mutationpp/Mutationpp/blob/c9a924fde43216e0777a918dc5042eaa18ae98b5/CMakeLists.txt#L66-79) and they function as expected. I duplicated this behavior in my commit.
