### ISSUE TITLE
Phantom jobs in CI tests

### ISSUE THREAD

**Issue by jbscoggi** [mutationpp/Mutationpp#200]
In recent PRs, I've noticed that 4 checks are never run.  Even more odd is that I can't find these jobs anywhere in the `.github/workflow` files.  In particular these are:

- build_linux (ubuntu-16.04, Debug, clang clang++)
- build_linux (ubuntu-16.04, Debug, gcc g++)
- build_linux (ubuntu-16.04, Release, clang clang++)
- build_linux (ubuntu-16.04, Release, gcc g++)

Beyond just being weird, it stops automatically merging because not all checks can pass (since they are never run).  As an example, take a look at recent PRs, including #186.  @rdbisme, perhaps you have an idea of what's happening?

**Comment by rdbisme** [comment]
Ehi @jbscoggi. I think it's  a bug of Github Actions: https://github.community/t/is-there-a-way-to-delete-or-hide-old-renamed-workflows/16281/35

**Comment by rdbisme** [comment]
Oh wait, [this](https://github.com/actions/runner/issues/1303) looks related

**Comment by rdbisme** [comment]
Fixed! :)

**Comment by jbscoggi** [comment]
Thanks @rdbisme!
