### ISSUE TITLE
bprime executable hangs 

### ISSUE THREAD

**Issue by Numedi** [mutationpp/Mutationpp#209]
Hello everyone, 

First of all, thank you for developing Mutation++ and make it so easily accessible. 
I have been recently interested into using mutation++ to compute bprime tables for atmospheric reentry problems, but using the latest version, the executable hangs (more precisely, it has problem to compute the mixture equilibrium in the surfaceMassBalance function) even for example mixture files such as the ones provided in the training-materials repository. 

Comparing the function with earlier version of M++ (such as the one provided inside PATO), I remarked that the mixture never load the edge composition in the main function. I think that adding : 

_mix.getComposition(opts.boundary_layer_comp, Yke.data(), Composition::MASS);_

at the beginning of the function solved my problem.

Could you tell me if there is effectively an issue in the main function of bprime.cpp of the current version or if I just have been using the executable wrong the whole time?

Sincerely, 
Vincent LE MAOUT

**Comment by BBArrosDias** [comment]
Hi Numedi, 

That seems right.
Could you commit your fix and make sure all tests pass? 

Cheers,
Bruno
