### ISSUE TITLE
Electron mass lacks precision

### ISSUE THREAD

**Issue by mgoodson-cvd** [mutationpp/Mutationpp#210]
The electron mass defined as 5.5e-4 g/mol [here](https://github.com/mutationpp/Mutationpp/blob/d37d3c8f808ff356ce75235355aa8c7f8b77cf29/data/thermo/elements.xml#L5) in `elements.xml` is lacking in precision. The value defined [in the NASA-9 thermodynamics database](https://github.com/mutationpp/Mutationpp/blob/d37d3c8f808ff356ce75235355aa8c7f8b77cf29/data/thermo/nasa9.dat#L167) is 5.48579903e-4 g/mol, which agrees well with [NIST CODATA value](https://physics.nist.gov/cgi-bin/cuu/Value?mme|search_for=electron) of 5.4857990888e-4 g/mol.

Is there some reason that 5.5e-4 g/mol was used rather than a more precise value? If not, can I update this to use the value, either to match the NASA-9 value or the more recent CODATA value? This is causing issues when moving between Mutation++ and another code which is using the more precise NASA-9 electron mass for other calculations.

**Comment by jbscoggi** [comment]
Nope, no reason other than I guess I was feeling lazy that day!  Please submit the PR with the correct value and I'll merge ASAP.  Thanks!

**Comment by mgoodson-cvd** [comment]
Will do. The fun thing about this one-line change is that it breaks several of the unit tests...

I'll try to get them sorted out before I push anything.

**Comment by mgoodson-cvd** [comment]
Any preference on whether to use the older NASA-9 value for the electron mass or the newer 2018 CODATA value? 

Also, some of the [other constants in Constants.h](https://github.com/mutationpp/Mutationpp/blob/d37d3c8f808ff356ce75235355aa8c7f8b77cf29/src/general/Constants.h#L48-56) are out of date with the 2018 CODATA values; e.g., `NA = 6.0221415E23` but [CODATA value](https://physics.nist.gov/cgi-bin/cuu/Value?na) is `NA = 6.02214076E23`. Again, updating them will subtly change results and probably break more unit tests... If you want me to update all the constants, I can make a new issue.

**Comment by mgoodson-cvd** [comment]
While most of the unit tests were easy to fix, the [comparisonTest](https://github.com/mutationpp/Mutationpp/blob/d37d3c8f808ff356ce75235355aa8c7f8b77cf29/tests/c%2B%2B/test_comparisons.cpp) is not. It is comparing against [stored data](https://github.com/mutationpp/Mutationpp/tree/d37d3c8f808ff356ce75235355aa8c7f8b77cf29/tests/c%2B%2B/comparisons) (presumably generated with Mutation++?), in a certain format that sets the tolerance for the test, etc. @jbscoggi do you have a script that generates this data easily? Otherwise this will be a pain to update otherwise. I did think about just increasing the tolerance...

I'll push what I've got (which uses the NASA-9 electron mass) and you can take a look.
