### ISSUE TITLE
licensing 

### ISSUE THREAD

**Issue by Bratac7** [mutationpp/Mutationpp#223]
Hello, 
In the CMakelist.txt or README files I see Mutationpp is "GNU Lesser General Public License" license, but in the folder I see also a COPYING file for a "GNU General Public License"? why do you have the COPYING file reffering to the GPL if the code is LGPL ?
Can you clarify the license type of Mutationpp please?
Thanks a lot!

**Comment by jbscoggi** [comment]
Hi @Bratac7, the combination of the COPYING and COPYING.LESSER are required for the LGPL since the COPYING.LESSER is just an addendum to the COPYING document.  Mutation++ is LGPL v3.  Thanks for the question.
