### ISSUE TITLE
Python package doesn't build or instructions are missing

### ISSUE THREAD

**Issue by jbscoggi** [mutationpp/Mutationpp#226]
**My OS is**: macOS

**OS Version:** 12.6.3

 
**Cmake Version:** 3.23.1

**Mutation++ origin**

git clone https://github.com/mutationpp/Mutationpp.git

**Mutation++ build steps**

1. `cd root_dir`
2. `mkdir build`
3. `cd build`
4. `ccmake ..` turn `BUILD_PYTHON_WRAPPER` ON, change install directory to a local install directory 
5. `make install`
6. `cd root_dir`
7. `pip install -e .`

**Comments**
The above steps do not produce any errors and the library compiles just fine.  The python package also is produced and can be imported.  However, upon `import mutationpp as mpp`, the following error is 

```bash
Traceback (most recent call last):
  File "some_script.py", line 3, in <module>
    import mutationpp as mpp
  File "path_to_root/interface/python/mutationpp/__init__.py", line 1, in <module>
    from ._mutationpp import *
ModuleNotFoundError: No module named 'mutationpp._mutationpp'
```

After reviewing the make logs, it's clear that the pybind11 module is never compiled, meaning no target _mutationpp is produced.  I think this is either a bug or the proper build instructions are not available.  Note, in the root `CMakeLists.txt`, the `BUILD_PYTHON_WRAPPER` option is not actually used.  Instead, it is relying on `SKBUILD` being defined in order to correctly add the `interface/python`and `thirdparty/pybind11` subdirectories.  Presumably this variable is defined when running `pip install -e .` by scikit-build, however these directories never seem to be traversed, and nothing gets compiled.  @rdbisme, any ideas?

**Comment by jbscoggi** [comment]
@rdbisme I just realized this actually has to do with trying to pip install in development mode with the -e option.  It seems this is the problem.  Without the option, it works fine...

**Comment by rdbisme** [comment]
Hello @jbscoggi, you just need to do: `pip install -e .` in the root of the repo. The manual build steps should not be required. 

I just tried and `import mutationpp` works.

So the instructions to build the Python package are:

`pip install -e .` 

in the root of the repo.

**Comment by jbscoggi** [comment]
Hey @rdbisme, yes this is what I tried.  For some reason it does not work for me with the -e option but it did without it.  I'm going to close since this is probably an issue with my python setup rather an M++.  Thanks.

**Comment by Fratorhe** [comment]
Hey, sorry for re-opening this, but I am having the exact same issue of @jbscoggi 
My OS is: Ubuntu
OS Version: 20.04
Cmake Version: 3.22.1
Python: 3.11.8 (with Anaconda)

If I install the package using `pip install .` it works, if I add the "-e", I get the same error of JB.
