### ISSUE TITLE
Update pybind11 to v2.10.4

### ISSUE THREAD

**Issue by mgoodson-cvd** [mutationpp/Mutationpp#230]
Required for pybind11 to work with python 3.11.4 in ubuntu 22.04 for CI/CD

See failure [here](https://github.com/mutationpp/Mutationpp/actions/runs/5425200097)

**Comment by mgoodson-cvd** [comment]
I'm going to update this to use git-subrepo (similar to the way you've done catch and eigen) rather than a "local" git submodule (.gitmodules was [pointing to `../../pybind/pybind11`](https://github.com/mutationpp/Mutationpp/blob/4cb6e3a05c15f49ffd346dc9f185ccc3459728b0/.gitmodules#L3) rather than https://github.com/pybind/pybind11). I'll stack this on #211 as well.

**Comment by rdbisme** [comment]
Hello @mgoodson-cvd. Thanks a lot for your work. Any chance you can put this in a separate PR? That way I cann approve it. The "scientific" part is @jbscoggi realm! :)

**Comment by mgoodson-cvd** [comment]
Sure. Okay if I combine with #229 so that the CI/CD will pass?

**Comment by rdbisme** [comment]
Yep!
