### ISSUE TITLE
C++ compling problem

### ISSUE THREAD

**Issue by Johnzqm** [mutationpp/Mutationpp#235]
**Hi, My OS is Linux. I have already installed Mutation++ and configured it based on the installation guide. However when I try to compile the example in c++/O2_dissociation, it says that mutation++ No such file or directory. How can I solve it.? Thanks very much.**

**Comment by rdbisme** [comment]
@Johnzqm can you please follow the issue template for a build issue?

**Comment by rdbisme** [comment]
Closing. Reopen with the template filled: that will help us helping you :)
