### ISSUE TITLE
"MACOSX_RPATH is not specified for the following targets" for MacOs

### ISSUE THREAD

**Issue by BBArrosDias** [mutationpp/Mutationpp#26]
when do the cmake on the mac operating system the following  warning comes out:

CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   mutation++
   mutation++_fortran

**Comment by BBArrosDias** [comment]
The solution is to include this command on the CMakeLists.txt:

if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    set(CMAKE_MACOSX_RPATH 1)
endif()

**Comment by jbscoggi** [comment]
Solved by #28
