### ISSUE TITLE
Python package in spyder

### ISSUE THREAD

**Issue by enrico1193** [mutationpp/Mutationpp#271]
Hi everyone, it is not an issue but more of a curiosity. I have always had some problems using the M++ Python package with Spyder. In particular, the only version that seems to work is 5.0.5, but for the rest the M++ package gets stuck when calling the "setState" or defining the "mixture(MyMixtureOptions)", especially when using the equilibrium state model. At one point I would like to upgrade my Spyder version so I was wondering if someone experienced the same problem and knows how to fix it. For instance, if there is some spyder dependency may create troubles to the M++ package.

I think the problem is correlated to spyder since I do not have any problems in running the package using python directly from terminal. I tried both Catalina 10.15.7 and Sequoia 15.0  but same story. Thank you!

**Comment by enrico1193** [comment]
Never mind, I think I finally found the problem!

**Comment by rdbisme** [comment]
If you can, elaborate on the problem. it might be useful to other users

**Comment by enrico1193** [comment]
Sure! The problem is related to Spyder's graphic backend settings. If QT is selected then it gets stuck otherwise it works
