### ISSUE TITLE
bprime calculation seems inconsistent with published works

### ISSUE THREAD

**Issue by crema-lida** [mutationpp/Mutationpp#273]
In `Thermodynamics::surfaceMassBalance`, the wall element fractions is initialized to be a combination of the boundary layer gas fractions and the pyrolysis gas fractions, using Bg as a weighting factor,  which seems like a reasonable but rough estimate of the wall element fractions. No further iteration/correction is performed thereafter. This approach does not appear to be documented in the existing literature on ablation modeling. Does it mean that wall element fractions need not be solved along chemical equilibrium? Can anyone provide insight into the validity of this calculation approach?

**Comment by grgbellasvki** [comment]
The elemental mass fractions at the wall are obtained from solving the elemental mass balances with B'c = 0.
The "additional iteration" idea is an interesting one. It has been applied in the past for similar problems with slightly different methodology. For verification you can refer to the paper on Mutation or here: http://dx.doi.org/10.1016/j.ast.2017.02.025

I suggest we move this to the discussions section. Can you please provide evidence supporting the title of your post?
