### ISSUE TITLE
Radiative processes

### ISSUE THREAD

**Issue by amorosej** [mutationpp/Mutationpp#41]
Hi, I am about to add radiative processes (bound-bound transitions, radiative recombination...) so I think we should agree on a convention for mutation. 
1) A label like "hv" could be used in reaction formulae to denote a photon.
2) The number of photon on each side of the reaction should be stored in a member of the reaction class (one integer for reactants, one for products). It allows to design a "radiative" branch that can be added at the root of the reaction classification tree. I have a draft but we should discuss it.
Once the reaction type is found, the radiative processes can actually be handled as any other reaction, so these small modifications should be enough.

**Comment by jbscoggi** [comment]
Hey @amorosej, yes I think you are on the right track using `hv`.  This should be easy enough to handle, but will require some updates on how reactions are parsed, etc.  We should also figure out how the radiation model can be incorporated and remain consistent.  I'll be there next week and we can talk about some more specifics.

**Comment by jbscoggi** [comment]
Seems like a dead issue, closing...
