### ISSUE TITLE
Interfacing Mutationpp with COOLFluiD

### ISSUE THREAD

**Issue by lkampoli** [mutationpp/Mutationpp#51]
Hello, 
I successfully compile and install Mutationpp, all tests, docs and fortran interface are ok.

Then, I try to interface to COOLFluiD as with the previous version, which however doesn't rely on Eigen.
Since I get an error: 

**/home/lcampoli/Mutationpp/install/include/mutation++/MultiPhaseEquilSolver.h:33:30: fatal error: eigen3/Eigen/Dense: No such file or directory
 #include <eigen3/Eigen/Dense>**

I'm wondering whether I should change something in the Mutationpp-COOLFluid interface process?
For example, should I install Eigen in COOLFluiD? Or it is just a problem of include_dir visibility? In this case, how can I make it visible system-wide?

Have you encountered this issue?

Regards,
Lorenzo

**Comment by jbscoggi** [comment]
Hey @lkampoli, this sounds like a problem with the include directory for Eigen in the COOLFluid build scripts.  Make sure that it correctly points to the correct Eigen folder.

**Comment by jbscoggi** [comment]
Hey @lkampoli, did you figure this out?  If not, look at my response to #64 and see if that helps.

**Comment by lkampoli** [comment]
Yes, sure, of course it was the include. Actually, I use catch and eigen system wide, so I don't have any issue, at least on my laptop. On the university server, I fix it in the .bashrc. 
The other issue, now is some segmentation fault in the CF run ... while in the old version of M++ does not occur, but I need to investigate more about this.

Thank you,
Lorenzo

**Comment by jbscoggi** [comment]
OK good.  No idea about CF unfortunately.... :( Good luck.
