### ISSUE TITLE
Star notation bug

### ISSUE THREAD

**Issue by amorosej** [mutationpp/Mutationpp#58]
Hi,
There is a mismatch of energy units in the constructor used for the "star notation" feature. I will make a pull request very soon for this.

**Comment by amorosej** [comment]
Okay, so I corrected the mistake and tried to run the tests. I fortuitously found a bug in the code after the following test failed : "11 - DiffusionMatrix yields diffusion fluxes which sum to zero".

The error comes from a division by (1-xi) in the Ramshaw diffusion matrix. When a species "i" is dominant, xi rounds off to 1.0 and then you're screwed. It happens in the test with the Argon state-to-state mixture, but you have the same problem with a mixture comprised of just three species {A, A+, e-}, because the ion lies high in energy. Before correcting the star notation the error was not occurring because the excited levels were artificially lowered, so their equilibrium molar fractions were not negligible.

Could we set the diffusion coefficient to zero in such a case ?

**Comment by jbscoggi** [comment]
Yes I see what you mean:
```cpp
// Form the matrix
for (int j = 0; j < ns; ++j) {
     m_Dij.col(j).fill(-Y[j]/X[j]*(1.-Y[j])/(1.-X[j])*Dim(j));
     m_Dij(j,j) -= m_Dij(j,j)/Y[j];
}
```
If you look at the definition of Dim,
```math
D_{im} = \frac{(1-x_i)}{\sum_{j\ne i}x_j/\mathscr{D}_{ij}}
```
then actually you see that the `1.-X[j]` should actually cancel out.  So maybe a better idea is just to not use the `Dim` but the partial computation of `Dim` which does not have the `1.-X[j]` term.  I will do this now and submit a PR.  Once that is merged, you can merge with your branch and see if it's working...

**Comment by jbscoggi** [comment]
OK, #62 should have fixed the problem.  Go ahead merge the latest master into your branch and see if that fixes the test case with your modifications.

**Comment by amorosej** [comment]
Ok, the test passes. I make the pull request.
