### ISSUE TITLE
Compiling SU2 with link to Mutation++

### ISSUE THREAD

**Issue by CatarinaGarbacz** [mutationpp/Mutationpp#64]
Hello,
after successfully compiling and running Mutation++ by itself, I am now trying to compile SU2 with the link to Mutation++ by running the command:

$ ./configure --prefix=/home/catarina/Codes/SU2-mut/SU2-NEMO/ --enable-mpi --with-cc=/usr/bin/mpicc --with-cxx=/usr/bin/mpicxx CXXFLAGS="-O3 -std=c++0x" **--with-Mutationpp-lib=/home/catarina/Codes/Mutation++/mutation++/install/lib --with-Mutationpp-include=/home/catarina/Codes/Mutation++/mutation++/install/include/mutation++** 

However, when running **$make**, I came across the following error:

**/home/catarina/Codes/Mutation++/mutation++/install/include/mutation++/MultiPhaseEquilSolver.h:33:30: fatal error: eigen3/Eigen/Dense : No such file or directory**

So, I tried to include the path to the file by running, instead:

**$make -I /home/catarina/Codes/Mutation++/mutation++/install/include/eigen3/Eigen**

And I got the same error. Any tips on how to go around this problem? @jbscoggi

**Comment by jbscoggi** [comment]
Hey @CatarinaGarbacz, you were close I think.  Try 
```bash
make -I /home/catarina/Codes/Mutation++/mutation++/install/include/
```
and see if that works.

**Comment by CatarinaGarbacz** [comment]
No, same error

**Comment by jbscoggi** [comment]
Sorry, I think I miss understood before, you cannot add an include path as an argument to make AFAIK.  Instead, you should add this in the configuration of SU2.  Try something like this when you call `./configure`:
```
CXXFLAGS="-O3 -std=c++0x -I /home/catarina/Codes/Mutation++/mutation++/install/include/"
```

**Comment by CatarinaGarbacz** [comment]
We've made some progress. It was able to get to the next error:

**../src/CGasKineticSchemeBGK.cpp:3:21: fatal error: lapacke.h: No such file or directory**

I would follow the same strategy to solve this error but, if I'm looking at it right, I am not being able to find any **lapacke.h** file in Mutation++ directory (especially not with an "e" lapack**e**)

**Comment by CatarinaGarbacz** [comment]
Hi JB,

sorry to bother again, could you help me with this additional error?

./src/CMutationpp.cpp: In member function ‘virtual std::vector<double> CMutationpp::GetMaxwellMoment(short unsigned int) const’:
../src/CMutationpp.cpp:225:14: error: ‘const class Mutation::Mixture’ has no member named ‘mixtureFrozenMaxwellMoment’

**Comment by jbscoggi** [comment]
Hey @CatarinaGarbacz , the first problem is purely an SU2 issue I believe since we don't use lapacke.h in M++ and the error is coming from an SU2 source file.

As for the second issue, I'm not sure what function `mixtureFrozenMaxwellMoment` is.  Perhaps this is something that was in your (or Dr. Fossati's) version of M++?  From the error, it seems that you are using the main version of M++ but the version of SU2 that you have is expecting another version which had the  `mixtureFrozenMaxwellMoment` function.  But this is just a guess...
