### ISSUE TITLE
Steady state pyrolysis model for GSI

### ISSUE THREAD

**Issue by grgbellasvki** [mutationpp/Mutationpp#7]
This issue aims to the addition of an approximate model for bulk pyrolysis to the surface and mass balance, as seen by the gas phase.
The steady state assumption implies that the recession velocity of the "pyrolysis layer"  is equal to the surface recession. This velocity plus the char to virgin density ratio (phi) determines the mass flux of the pyrolysis gases, which are added to the mass and energy balance, and eventually increase the blowing velocity in the gas phase, further protecting the surface. The knowledge of the elemental or chemical composition of the pyrolysis gases is an input to the model, while the temperature of the pyrolysis gases is equal to the surface temperature.

**Comment by jbscoggi** [comment]
Hey @grgbellasvki, this issue seems a little dead.  Is it safe to delete it?  If not, can you add a description?

**Comment by grgbellasvki** [comment]
Short description added. I will close it in a couple of months if no one implements it and will reopen it on request.

**Comment by grgbellasvki** [comment]
Closing this issue as the described feature seems that it is not needed. Will reopen on request.
