### ISSUE TITLE
Jacobian segmentation fault

### ISSUE THREAD

**Issue by grgbellasvki** [mutationpp/Mutationpp#74]
I have noticed a segmentation fault when calling the jacobianRho method.
Furthermore there is a bug for some jacobian terms for reactions like:
N2+N=N+N+N when they are not considered as third body. 

I have fixed the second issue and currently working on the first one. A unit test for the jacobians for a "fake" air5 mixture will be also committed.

**Comment by jbscoggi** [comment]
Since this seems to be a very rare bug, I think we can remove the v1.0.0 milestone, and include the fix as a bug fix to v1.0.0 when it is ready.

**Comment by jbscoggi** [comment]
After discussing with @grgbellasvki, we came up with a nice solution that can be incorporated into the current tests.  I will take ownership of this bug and work on it.
