### ISSUE TITLE
Selecting energy tranfer mechanism

### ISSUE THREAD

**Issue by lkampoli** [mutationpp/Mutationpp#78]
Dear all,
I was wondering whether it is possible to select the energy transfer mechanism.
For example, only consider VT (OmegaVT) and not the others and so on ...
As far as I understand, there is not such option and consequently I don't see in MixtureOption something like opts.setEnergyTransfer. It means that all available mechanisms defined in the concrete class of the StateModel will be considered?

Thanks,
Lorenzo

**Comment by jbscoggi** [comment]
Hey @lkampoli, that is correct at the moment.  The only way to "select" which terms to include would be to change this in the concrete state model class.  In principle, it is not very hard to add an option for this though.  The basic idea would be to self register each class that represents a transfer term with a given name, and then provide an option which takes a list of names (terms) to include.  We could then move the selection of terms out of the concrete state model classes, and into the base class.  The concrete SM classes would then simply provide the base class with the default terms for the given model as a list.  The only real sticking point is how to associate each term with the correct energy modes, though this could be done with some string parsing.  Here is a concrete example:

1. Make the energy transfer term classes self registering, ie: give OmegaVT the name "OmegaVT", etc
2. Provide an option in MixtureOptions, setEnergyTransferTerms(const std::string& terms).  This could take a comma separated list like "OmegaVT(0-1),OmegaCV(0-1)" where the 0-1 indicates the energy is taken from mode 0 and placed in mode 1 (positive direction).
3. The base StateModel class could then be responsible for parsing this string and instantiating the objects.
4. The concrete StateModels would then simply pass the default value of this string to the base class which it would use if the option is not set in MixtureOptions.

So, there is a little bit of work to do to get it to work, but not so bad...

**Comment by lkampoli** [comment]
@jbscoggi  thank you for hints. Yes, I like such OOP organization. For the moment, I just added Variable Soft Sphere (VSS) and Forced Harmonic Oscillator (FHO) more ore less hard-coded in the transfer environment. 
Anyway, as you said, in principle, the work to do is well-defined.

**Comment by jbscoggi** [comment]
It seems this issue was settled a while ago, so I'm closing.
