### ISSUE TITLE
Missing data for uncommon gases

### ISSUE THREAD

**Issue by elsalaaarsson** [mutationpp/Mutationpp#85]
Hello!

I am doing research into a laser ablation thruster for cubesats, and am trying to find data on the gases that my polymer produces to put into my OpenFOAM and dcmcFoam+ simulations. After trying, and failing, to find viscosities and Prandtl numbers for my different components online and in books, I tried using mutation++ and am super impressed by the software, although it doesn't seem to have data on all the gases in my mixture and was wondering if you might know if it exists and, if so, where I can find it to download. 

My mixture consists of 18N2, 13H2, 16CO, 13HCN, 5NH3, 2H2CO, CH4, 8C2H2 and 3C3H4. 

Thank you!

**Comment by jbscoggi** [comment]
Hey @elsalaaarsson,  just to clarify, the species are N2, H2, CO, HCN, NH3, H2CO, CH4, C2H2, and C3H4 and the numbers that prefix are their relative amounts?

**Comment by elsalaaarsson** [comment]
Yes, exactly! Although I made a mistake, and the last one shouldn't be C3H4, but instead C2H4, also known as Ethylene.

**Comment by jbscoggi** [comment]
OK, cool.  Here is a preliminary mixture file definition:

```xml
<mixture thermo_db="NASA-9-New">
    <species>
        N2 H2 CO HCN NH3 HCHO CH4 C2H2 C2H4
    </species>

    <element_compositions default="ablation">
        <composition name="ablation"> 
            N2:18, H2:13, CO:16, HCN:13, NH3:5, HCHO:2, CH4:1, C2H2:8, C2H4:3
        </composition>
    </element_compositions>
</mixture>
```

This uses a custom database that we have created in a [recent paper](https://www.researchgate.net/publication/314649282_Thermodynamic_properties_of_carbon-phenolic_gas_mixtures).
I am assuming by H2CO you mean formaldehyde, which is denoted as HCHO in this database.

As for the transport properties, I will need to investigate a little further, but you can already compute thermodynamic properties with that mixture.

**Comment by jbscoggi** [comment]
Note, you need create a mixture file (for example laser_ablation.xml).  Then you can compute equilibrium properties with mppequil.

**Comment by jbscoggi** [comment]
Hey @elsalaaarsson, here is an updated mixture model which uses the simple NASA-9 database.  Note there are a few differences in the species names.

```xml
<mixture thermo_db="NASA-9">
    <species>
        N2 H2 CO HCN NH3 HCHO,formaldehy CH4 C2H2,acetylene C2H4
    </species>

    <element_compositions default="ablation">
        <composition name="ablation"> 
            C  :  0.25,
            H  : 0.416667,
            N  :  0.25,
            O  : 0.0833333
        </composition>
    </element_compositions>
</mixture>
```

With this, almost everything you need is available in M++ to compute transport as well.  If you can just find the dipole-polarizability of NH3, that is the only piece of information we need to complete the model.  Can you find that and get back to me?  If so, I will be happy to add the necessary updates to the collision integral database, and then you can compute transport properties, such as viscosity.

**Comment by elsalaaarsson** [comment]
Hi, @jbscoggi ! Thank you so much for your help. 
When I did as in your first message, I got this warning message: 
Warning: the NASA-9-New thermodynamic database is assembled from a collection of sources and is still being vetted. See Scoggins et al. Aerospace Science and Technology 66:177-192, 2017. for more details.  The name of this database may change in the future.

I will try the updated approach and have a look for the dipole-polarizability of NH3 and get back to you. 

Best wishes,
E

**Comment by elsalaaarsson** [comment]
This might be a stupid question, but after I have run ...
`mppequil laserAblation2.xml`
(The code in your recent post was put in the new file laserAblation2.xml)
... I got no messages at all. How do I extract the information about the mixture? 

I am using Ubuntu and am doing this straight in Terminal. Very new to all of this, so please bear with me!

**Comment by jbscoggi** [comment]
Here is some documentation on [mppequil](https://github.com/mutationpp/Mutationpp/blob/master/docs/mppequil.md#top).  Otherwise, you can type `mppequil -h` for the same help.

Best

**Comment by elsalaaarsson** [comment]
Okay, so I ran the command `mppequil laserAblation2.xml` which just gave me a bunch of empty rows and then I did:
`mppequil -T 1548 -P 1029.4 --species-list "N2 H2 CO HCN NH3 HCHO CH4 C2H2 C2H4" --elem-x "C:0.25, H:0.41666667, N:0.25, O:0.08333333" -m 3,5,9,24,32,33 >mixture.txt`
which gives me the following error message:

> Missing the following species!
>    HCHO
> 
> M++ error: invalid input.
> input: species list = N2 H2 CO HCN NH3 HCHO CH4 C2H2 C2H4
> Could not find all required species in the thermodynamic database.

**Comment by elsalaaarsson** [comment]
Do I need to do anything to get that custom database that the paper you referenced was discussing?

**Comment by jbscoggi** [comment]
Can you try:

```
mppequil -T 1548 -P 1029.4 -m 3,5,9,24,32,33 laserAblation2 > mixture.txt
```

That will probably still give you errors because the transport data is not ready.  If you only ask for thermodynamic properties, you should be good.

**Comment by elsalaaarsson** [comment]
Yes thank you, you're absolutely right, it works when I remove 32 and 33 from the command. 

I'm still looking for reliable data on the dipole-polarizability of NH3, will get back to you when I find it.

Thank you for all your help!

**Comment by elsalaaarsson** [comment]
According to the cited article, the dipole-polarizability of ammonia (NH3) is as follows:
Perpendicular: 13.6, Parallel: 15.3, Average: 14.2

https://mro.massey.ac.nz/bitstream/handle/10179/1694/02_whole.pdf

**Comment by elsalaaarsson** [comment]
@jbscoggi Would you be able to update the database with these numbers so I can calculate the thermal conductivity and viscosity as well? 

Kind regards,
Elsa

**Comment by jbscoggi** [comment]
Perfect, I will take care of that this weekend and get back to you.

**Comment by elsalaaarsson** [comment]
Thank you so much! Have a good weekend!

**Comment by jbscoggi** [comment]
Hey @elsalaaarsson, we had a few issues to work on to get our testing framework working again but that seems to be fixed.  I have added a new pull request #90 which should give you everything you need.  It might take an hour or two for all the current PRs to pass through the pipeline, but once it is through I'll let you know.

**Comment by jbscoggi** [comment]
Hi @elsalaaarsson, the PR has gone through, you can now do a `git pull` in your mutation++ directory to update your version.  Let me know if you have any problems.  If all goes well, I will close this issue.

**Comment by elsalaaarsson** [comment]
Hi, @jbscoggi ! When doing `git pull`, it says that it's already up-to-date but still won't work. I copied the changes you made to the transport data file into the one in my installation as well and made a file differences check to make sure our files are identical, which they were. The errors it gives me are "Missing collision integral...".

**Comment by rubendibattista** [comment]
@elsalaaarsson what is the last commit when you do `git log`?

**Comment by elsalaaarsson** [comment]
commit 433e4ca82f043004a1d6300188ddef8a5194fe86
Merge: 43f3a98 def2878
Author: James B. Scoggins <james.scoggins@vki.ac.be>
Date:   Thu Oct 25 16:47:48 2018 +0200

**Comment by rubendibattista** [comment]
Mmmh, are you sure to be using the right repository? The last commit is about 1 year old. 

`git remote get-url origin`?

**Comment by elsalaaarsson** [comment]
@rubendibattista No, as a matter of fact there were several things I had to add to my transport data file, so I might have an old version. This is what `git remote get-url origin` returned: https://sync.vki.ac.be/mpp/mutationpp.git

**Comment by rubendibattista** [comment]
Ok, your repo is pointing to the old one from VKI.

You have two solutions here:

* Just clone again the repo from here on Github and compile again.

* Update your repo with the correct url:
`git remote set-url https://github.com/mutationpp/Mutationpp.git`

And the your `git pull` should work.

**Comment by rubendibattista** [comment]
@jbscoggi you should probably do something about the old repo.

**Comment by elsalaaarsson** [comment]
Is this the correct version of the installation? https://github.com/mutationpp/Mutationpp/wiki/installation-guide
Because trying to install this, I noticed that this step:
```
cd $MPP_DIRECTORY
python scripts/install_dependencies.py
```
doesn't work since there is no file called install_dependencies.py in the scripts folder.

I tried this since the command `git remote set-url origin https://github.com/mutationpp/Mutationpp.git` didn't work as it wasn't the correct use of set-url and needed an additional input.

Thanks for all your help! @rubendibattista and @jbscoggi

**Comment by rubendibattista** [comment]
Mmmh, nope. I forgot to update that part. If you want to use the `Eigen` version that is shipped with `mutation`, it should work straight away when you run the configuration with `cmake`. You don't need to install the dependencies manually. It should automatically find `Eigen` in the right `thirdparty` folder.

Just skip that step and go to the next one and come bac to us if you have problems.

**Comment by elsalaaarsson** [comment]
I'm still getting errors. What I did was I installed the new version following the instructions in the link I sent, but skipping the step I had issues with and just continued with the installation. 

I then created a file called laserAblation.xtl including the following:
```
<mixture thermo_db="NASA-9"> 
    <species> 
        N2 H2 CO HCN NH3 HCHO,formaldehy CH4 C2H2,acetylene C2H4 
    </species> 
  
    <element_compositions default="ablation"> 
        <composition name="ablation">  
            C  :  0.25, 
            H  : 0.416667, 
            N  :  0.25, 
            O  : 0.0833333 
        </composition> 
    </element_compositions> 
</mixture> 
```
and run the command  `mppequil -T 1548 -P 1106507.818257603 -m 3,5,9,24 laserAblation > mixture.txt` which gives the error 
> mppequil: error while loading shared libraries: libmutation++.so: cannot open shared object file: No such file or directory

**Comment by elsalaaarsson** [comment]
I did also run `git pull`, but once again it just said that I already have the latest update.

**Comment by rubendibattista** [comment]
Are you on Fedora/CentOS? 

Can you paste here the output of: `echo $LD_LIBRARY_PATH`? 

And also the content of the install folder?

**Comment by elsalaaarsson** [comment]
No I'm using Ubuntu, v18.04.2

Here's the output:

/home/elsa/Mutationpp/install/lib:/home/elsa/OpenFOAM/ThirdParty-v1706/platforms/linux64Gcc/fftw-3.3.6-pl1/lib64:/home/elsa/OpenFOAM/ThirdParty-v1706/platforms/linux64Gcc/CGAL-4.9.1/lib64:/home/elsa/OpenFOAM/ThirdParty-v1706/platforms/linux64Gcc/boost_1_64_0/lib64:/home/elsa/OpenFOAM/ThirdParty-v1706/platforms/linux64Gcc/gperftools-2.5/lib64:/home/elsa/OpenFOAM/ThirdParty-v1706/platforms/linux64Gcc/ParaView-5.4.0/lib/paraview-5.4:/home/elsa/OpenFOAM/OpenFOAM-v1706/platforms/linux64GccDPInt32Opt/lib/openmpi-system:/home/elsa/OpenFOAM/ThirdParty-v1706/platforms/linux64GccDPInt32/lib/openmpi-system:/usr/lib/x86_64-linux-gnu/openmpi/lib:/home/elsa/OpenFOAM/elsa-v1706/platforms/linux64GccDPInt32Opt/lib:/home/elsa/OpenFOAM/site/v1706/platforms/linux64GccDPInt32Opt/lib:/home/elsa/OpenFOAM/OpenFOAM-v1706/platforms/linux64GccDPInt32Opt/lib:/home/elsa/OpenFOAM/ThirdParty-v1706/platforms/linux64GccDPInt32/lib:/home/elsa/OpenFOAM/OpenFOAM-v1706/platforms/linux64GccDPInt32Opt/lib/dummy:/home/elsa/Mutationpp/install/lib:/home/elsa/mutation++/install/lib

Did you mean the **build** folder? Its content is as follows:
CMakeCache.txt  CMakeFiles  cmake_install.cmake  install_manifest.txt  Makefile  src

**Comment by rubendibattista** [comment]
The content of `/home/elsa/Mutationpp/install`, please :)

**Comment by elsalaaarsson** [comment]
That doesn't exist haha, sorry... 
![Screenshot from 2019-07-09 12-07-51](https://user-images.githubusercontent.com/52160593/60883473-34ddc080-a242-11e9-9e11-2b73bdcc7dd0.png)

**Comment by rubendibattista** [comment]
Mmmh, so there are some problems with your configuration (and with our readme, see #93).

1. In your `$LD_LIBRARY_PATH` you have the old `/home/elsa/mutation++/install/lib`. This is probably set in your `.bashrc`. You probably should delete  it once the new version works to avoid path collision. You probably have a similar entry also in the `$PATH`.
2. Currently, with the new version, `mutation++` by default will install stuff in `/usr/local/{bin,lib/lib64,include}`. Why? Because this is the standard way of doing things :). So when you did `make install` it probably complained about you not having rights to do that and it did not install it. In order to install mutation in the classical way, you need to tell to cmake where to install it doing: `cmake -DCMAKE_INSTALL_PREFIX:PATH="$(realpath ../install)"`. This will install all mutation stuff in `/home/elsa/Mutationpp/install`
3. Once you correctly installed it, hopefully it should work. 

Can you please also paste the output of `echo $PATH`?

**Comment by elsalaaarsson** [comment]
Thank you! After the cmake command, do I need to do anything else?

This is my `echo $PATH` output:
/home/elsa/Mutationpp/install/bin:/home/elsa/OpenFOAM/ThirdParty-v1706/platforms/linux64Gcc/gperftools-2.5/bin:/home/elsa/OpenFOAM/ThirdParty-v1706/platforms/linux64Gcc/ParaView-5.4.0/bin:/home/elsa/OpenFOAM/elsa-v1706/platforms/linux64GccDPInt32Opt/bin:/home/elsa/OpenFOAM/site/v1706/platforms/linux64GccDPInt32Opt/bin:/home/elsa/OpenFOAM/OpenFOAM-v1706/platforms/linux64GccDPInt32Opt/bin:/home/elsa/OpenFOAM/OpenFOAM-v1706/bin:/home/elsa/OpenFOAM/OpenFOAM-v1706/wmake:/home/elsa/Mutationpp/install/bin:/home/elsa/mutation++/install/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

A question about this is that I have deleted all old mutation++ directories and checked the .bashrc file so it is updated but it still includes a mutation++ path. Is there a way for me to change this?

Once again, thank you so much for all your help!

**Comment by rubendibattista** [comment]
There's something indeed setting up those env variables. Check inside `.bashrc`, `.bash_profile` and `.profile` if there's something related to mutation. Then open a new terminal shell and:

* Remove the `build` directory
* Create a new one
* Follow the install instructions skipping the dependencies step, and instead of just doing `cmake ..` you do the cmake command I gave you in the previous comment (`cmake -DCMAKE_INSTALL_PREFIX:PATH="$(realpath ../install)" .. `)
* Check now that `/home/elsa/Mutationpp/install` exists and contain `lib, bin, include` directories.

If everything checks out, you should be able to use now the new version.

**Comment by elsalaaarsson** [comment]
It's working!!! Thank you so much for all the help!

One last question; if I wanted to check the properties of all the components alone in my mixture, what would be the best way to do this? Do I need to create new .xml files for each component?

**Comment by jbscoggi** [comment]
Thanks @rubendibattista!  

@elsalaaarsson, for your last question.  The easiest would be to use mppquil but instead of specifying a mixture, use the --species-list and --thermo-db options.  For example, you could do

```bash
mppequil --species-list "NH3" --thermo-db "NASA-9" (other options here)
```

That should work!

**Comment by elsalaaarsson** [comment]
I keep getting a "floating point exception" error. I've tried a bunch of different formats but don't seem to be able to get it right. Would you be able to help me piece it together?

mppequil --species-list "NH3" --thermo-db "NASA-9" -T 1548 -P 1106507.818257603 -m 3,5,9,24,32,33 > NH3.txt

**Comment by jbscoggi** [comment]
Hmmm, indeed this is what I get...

```
mppequil --species-list "NH3" --thermo-db "NASA-9" -T 1548 -P 1106507.818257603 -m 3,5,9,24,32,33 
   rho[kg/m^3]    Mw[kg/mol]  Cp_eq[J/kg-K]     Hf[J/mol]      mu[Pa-s]  lambda[W/m-K]
       1.46412     0.0170305            nan             0   4.56633e-05            nan
```

There seems to be a bug with using only one species because if I get this if I add N2

```
mppequil --species-list "N2 NH3" --thermo-db "NASA-9" -T 1548 -P 1106507.818257603 -m 3,5,9,24,32,33 
   rho[kg/m^3]    Mw[kg/mol]  Cp_eq[J/kg-K]     Hf[J/mol]      mu[Pa-s]  lambda[W/m-K]
       1.93622      0.022522        2256.83             0   5.19549e-05       0.173736
```

I will add this as another issue.  I think for your original question of wanting data for your mixture.  This has been solved.  In the meantime, note that you can get some pure species quantities with mppequil using a mixture.  Take a look at the species properties available.
