### ISSUE TITLE
Update install instructions

### ISSUE THREAD

**Issue by rubendibattista** [mutationpp/Mutationpp#93]
- [x] `install_dependencies.py` was removed
- [x] On RHEL `LD_LIBRARY_PATH` should point to `lib64`.
- [x] `cmake` now needs the install prefix specified

Maybe before this we can discuss how to handle `thirdparty` in a smarter way to keep it up to date. e.g. on another project I download at configure time the third party libraries directly using `cmake`, but there's a problem here: with new `catch2`, tests fail.

**Comment by jbscoggi** [comment]
Hey @rubendibattista, I keep getting questions offline about the installation instructions not working any more.  Do you mind updating the instructions to match the new procedure and then we can have a separate discusson about how to handle thirdparty deps?

**Comment by rubendibattista** [comment]
Ok, I'll try to work on it as soon as I have a bit of free time.

**Comment by rubendibattista** [comment]
@jbscoggi Things in `/docs` are automatically updated with the stuff in the wiki? 

Because if they're duplicated, that would also generate a lot of confusion.

**Comment by jbscoggi** [comment]
Good point! I forgot all about the wiki.  I would prefer to move all documentation to docs and discontinue the wiki.  The main reason for this is that /docs can be versioned with the source allowing to maintain consistent docs over time.  I will try to go through the wiki soon and make sure there is nothing there that hasn't been moved to /docs and remove it.
