### ISSUE TITLE
Floating point error using only one species in mppequil

### ISSUE THREAD

**Issue by jbscoggi** [mutationpp/Mutationpp#94]
Refer to #85 for an example.

**Comment by elsalaaarsson** [comment]
Trying to run the same command as you in #85 I get the following:
```
mppequil --species-list "NH3" --thermo-db "NASA-9" -T 1548 -P 1106507.818257603 -m 3,5,9,24,32,3
   rho[kg/m^3]    Mw[kg/mol]  Cp_eq[J/kg-K]     Hf[J/mol]      mu[Pa-s]   rho[kg/m^3]
Floating point exception (core dumped)
```

**Comment by rubendibattista** [comment]
I think the different error depends on the compiler/OS. Probably on macOs it does not crash on floating point exception but instead returns a `nan`.

**Comment by elsalaaarsson** [comment]
Thanks, @rubendibattista , that would make sense.

**Comment by elsalaaarsson** [comment]
Hey, how is this bug coming along? :)

**Comment by jbscoggi** [comment]
Hey @elsalaaarsson, I'm sorry I have been very busy the last two weeks.  I will try and take a look at it this weekend.

**Comment by elsalaaarsson** [comment]
No worries!

**Comment by jbscoggi** [comment]
Hey @elsalaaarsson, I realize this is pretty late and you probably moved on but I just pushed a fix for this.  I hope it can still be helpful.
