### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by soy15** [mutationpp/Mutationpp#99]
Hello all,
I am having a installation problem. I did all steps which are written on mutationpp installation instructions, but on test step, when I write a checkmix air_11, there is a such error that I am having : 
"checkmix: error while loading shared libraries: libmutation++.so: cannot open shared object file: No such file or directory"
Can you help me with this issue?
Thank you in advance.

**Comment by rubendibattista** [comment]
Hello @soy15, 
Can you please paste all the steps you're following on your terminal from the beginning to the error? (Including all the output of the error)

Thanks! :)

**Comment by soy15** [comment]
--help-module <mod> [<f>]    = Print help for one module and exit.
  --help-module-list [<f>]     = List modules with help available and exit.
  --help-modules [<f>]         = Print cmake-modules manual and exit.
  --help-policy <cmp> [<f>]    = Print help for one policy and exit.
  --help-policy-list [<f>]     = List policies with help available and exit.
  --help-policies [<f>]        = Print cmake-policies manual and exit.
  --help-property <prop> [<f>] = Print help for one property and exit.
  --help-property-list [<f>]   = List properties with help available and
                                 exit.
  --help-properties [<f>]      = Print cmake-properties manual and exit.
  --help-variable var [<f>]    = Print help for one variable and exit.
  --help-variable-list [<f>]   = List variables with help available and exit.
  --help-variables [<f>]       = Print cmake-variables manual and exit.

Generators

The following generators are available on this platform:
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Watcom WMake                 = Generates Watcom WMake makefiles.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.

[soy@aglin21 build]$ cmake --version
cmake version 3.11.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
[soy@aglin21 build]$ sudo apt-get cmake

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for soy: 
sudo: apt-get: command not found
[soy@aglin21 build]$ sudo
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] file ...
[soy@aglin21 build]$ clear

[soy@aglin21 build]$ cd ..
[soy@aglin21 Mutationpp]$ module avail

----------------------------------------------------------------------------------------------------- /software/alternate/vkimodulefiles -----------------------------------------------------------------------------------------------------
ace/2013.4p1                                dakota/6.7                                  metacomptech/cfd++/16.1                     openfoam/2.3.1                              tecplot/360_2009
ace/2014.0p1                                draftsight/beta-v1r5.2                      metacomptech/cfd++/17.1                     openfoam/2.4.0                              users/alsalihi/ATPreDesign/2016
ansys/16.0                                  elmer/8.3                                   metacomptech/cfd++/18.1                     openfoam/3.0.0                              users/chatzigeordis/mutation++/V0.1
ansys/16.1                                  engauge/5.2                                 numeca/omnis/1.1dev28                       openfoam/3.0.1                              users/christju/batman/201604
ansys/16.2                                  freefilesync/6.8                            numeca/omnis/2.1                            openfoam/test                               users/christju/batman/201805
ansys/16.2.bis                              gambit/2.4.6                                numeca/omnis/2.2                            openfoam_user_contributed/3.0.1             users/christju/python_packages/batmanpy_dev
ansys/17.0                                  gcc/4.6.4                                   numeca/open/41_numeca_mpi                   openfoam_user_contributed/4.0               users/christju/python_packages/test_ci_cd
ansys/18.0                                  gcc/4.9.2                                   numeca/open/42_numeca_mpi                   openfoam_user_contributed/4.1               users/garciasanche/dakota-6.4.0
ansys/19.0                                  gcc/5.5.0                                   numeca/open/43_numeca_mpi                   openfoam_user_contributed/5.0               users/grossir/L1d_v2019
ansys/19.2                                  gitm/2.1                                    numeca/open/51_numeca_mpi                   openfoam_user_contributed/6                 users/maffulli/cado3.2
ansys/2019R1                                gmsh/2.8.5                                  numeca/open/52_numeca_mpi                   openfoam_user_contributed/v1706             users/maffulli/cado5
ansys/2019R2                                lms/sysnoise/5.6                            numeca/open/61_numeca_mpi                   openfoam_user_contributed/v1712             users/maffulli/cado-ad
aocc/1.2                                    lms/sysnoise/5.6_2012                       numeca/open/62_numeca_mpi                   openfoam_user_contributed/v1806             users/maffulli/openfoam_plus_v1612
aocc/1.3.0                                  matlab/2013a                                numeca/open/72_numeca_mpi                   openfoam_user_contributed/v1812             users/prinsier/arcc/2017
aocc_openfoam/5.x                           matlab/2015a                                numeca/open/81_numeca_mpi                   openmpi/1.6.5                               users/sans/netgen/5.3.1
aocc_openmpi/3.1.0                          matlab/2015b                                numeca/turbo/10.1                           paraview/4.2                                users/verstrae/cado-ad
auto/0.9.1                                  matlab/2016a                                numeca/turbo/10.2_vki_mpi                   parmetis/4.0.3                              users/verstrae/cado-ad-fedora27
automake/1.15                               matlab/2016b                                numeca/turbo/11.1_numeca_mpi                rgdas/r220                                  users/verstrae/cado-ad-parallel
cgal/4.9                                    matlab/2017a                                numeca/turbo/12.1_numeca_mpi                samcef/16.1                                 users/verstrae/cado-ad-parallel-fedora27
cgns/2.5.3                                  matlab/2017b                                numeca/turbo/13.2_numeca_mpi                samcef/16.1-i8                              varicad/2015
cmake/3.6.0                                 matlab/2018a                                numeca/turbo/9.1.3                          starccm/13.04                               varicad/2.05-1
cmake/3.9.6                                 matlab/2018b                                openfoam/2.1                                starccm/13.04r8                             vesta/1.0
comsol/5.0                                  matlab/2019a                                openfoam/2.2.0                              su2/6.1.0
dakota/6.0                                  metacomptech/cfd++/15.1                     openfoam/2.3.0                              teamviewer/10

------------------------------------------------------------------------------------------------------- /usr/share/Modules/modulefiles -------------------------------------------------------------------------------------------------------
4ti2-x86_64 dot         module-git  module-info modules     null        use.own

----------------------------------------------------------------------------------------------------------- /usr/share/modulefiles -----------------------------------------------------------------------------------------------------------
carat-x86_64                 lrcalc-x86_64                mpi/openmpi-x86_64           python-sphinx/python2-sphinx python-sphinx/python3-sphinx surf-geometry-x86_64

----------------------------------------------------------------------------------------------- /software/alternate/coolfluid/cf2/modulefiles ------------------------------------------------------------------------------------------------
cf2-2013.9/mpich                    cf2-2014.11/mpich                   cf2-2014.11/openmpi-optim           cf2-2014.11/rocks5/solver-openmpi   cf2-2015.11/openmpi-cuda            cf2-2015.11/openmpi-optim-llong
cf2-2013.9/mpich-optim              cf2-2014.11/mpich2                  cf2-2014.11/openmpi-optim-long      cf2-2014.11/solver-mpich            cf2-2015.11/openmpi-cuda-3.7.3      cf2-2015.11/openmpi-optim-long
cf2-2013.9/openmpi                  cf2-2014.11/mpich2-optim            cf2-2014.11/rocks5/mpich2           cf2-2014.11/solver-mpich2           cf2-2015.11/openmpi-cuda-3.7.3-K40  cf2-2015.11/rocks5/solver-mpich2
cf2-2013.9/openmpi-optim            cf2-2014.11/mpich-optim             cf2-2014.11/rocks5/openmpi          cf2-2015.11/f27/solver-openmpi      cf2-2015.11/openmpi-cuda-3.7.3-next cf2-2015.11/solver-openmpi-long
cf2-2013.9/solver-openmpi           cf2-2014.11/mpich-optim-long        cf2-2014.11/rocks5/solver-mpich2    cf2-2015.11/openmpi                 cf2-2015.11/openmpi-long
[soy@aglin21 Mutationpp]$ module load cmake/3.9.6 
	This module will set up aliases and environment variables
	for use cmake 3.9.6
[soy@aglin21 Mutationpp]$ cd build/
[soy@aglin21 build]$ cmake -DCMAKE_INSTALL_PREFIX:PATH=$(realpath ../install) ..
-- The CXX compiler identification is GNU 7.3.1
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Searching for Eigen3...
-- Configuring done
-- Generating done
-- Build files have been written to: /students/st_18_19/soy/Mutationpp/build
[soy@aglin21 build]$ make -j4 install
Scanning dependencies of target mutation++
[  4%] Building CXX object src/CMakeFiles/mutation++.dir/general/MixtureOptions.cpp.o
[  4%] Building CXX object src/CMakeFiles/mutation++.dir/general/Mixture.cpp.o
[  4%] Building CXX object src/CMakeFiles/mutation++.dir/kinetics/Kinetics.cpp.o
[  4%] Building CXX object src/CMakeFiles/mutation++.dir/kinetics/JacobianManager.cpp.o
[  6%] Building CXX object src/CMakeFiles/mutation++.dir/kinetics/RateLaws.cpp.o
[  8%] Building CXX object src/CMakeFiles/mutation++.dir/kinetics/RateManager.cpp.o
[  8%] Building CXX object src/CMakeFiles/mutation++.dir/kinetics/Reaction.cpp.o
[  9%] Building CXX object src/CMakeFiles/mutation++.dir/kinetics/ReactionType.cpp.o
[ 11%] Building CXX object src/CMakeFiles/mutation++.dir/kinetics/StoichiometryManager.cpp.o
[ 12%] Building CXX object src/CMakeFiles/mutation++.dir/numerics/Interpolators.cpp.o
[ 13%] Building CXX object src/CMakeFiles/mutation++.dir/thermo/ChemNonEqStateModel.cpp.o
[ 14%] Building CXX object src/CMakeFiles/mutation++.dir/thermo/ChemNonEqTTvStateModel.cpp.o
[ 16%] Building CXX object src/CMakeFiles/mutation++.dir/thermo/Composition.cpp.o
[ 17%] Building CXX object src/CMakeFiles/mutation++.dir/thermo/EquilStateModel.cpp.o
[ 18%] Building CXX object src/CMakeFiles/mutation++.dir/thermo/MultiPhaseEquilSolver.cpp.o
[ 19%] Building CXX object src/CMakeFiles/mutation++.dir/thermo/Nasa7Polynomial.cpp.o
[ 20%] Building CXX object src/CMakeFiles/mutation++.dir/thermo/Nasa9Polynomial.cpp.o
[ 22%] Building CXX object src/CMakeFiles/mutation++.dir/thermo/Nasa7DB.cpp.o
[ 23%] Building CXX object src/CMakeFiles/mutation++.dir/thermo/Nasa9DB.cpp.o
[ 25%] Building CXX object src/CMakeFiles/mutation++.dir/thermo/RrhoDB.cpp.o
[ 25%] Building CXX object src/CMakeFiles/mutation++.dir/thermo/ParticleRRHO.cpp.o
[ 27%] Building CXX object src/CMakeFiles/mutation++.dir/thermo/Species.cpp.o
[ 28%] Building CXX object src/CMakeFiles/mutation++.dir/thermo/SpeciesListDescriptor.cpp.o
[ 29%] Building CXX object src/CMakeFiles/mutation++.dir/thermo/SpeciesNameFSM.cpp.o
[ 30%] Building CXX object src/CMakeFiles/mutation++.dir/thermo/Thermodynamics.cpp.o
[ 32%] Building CXX object src/CMakeFiles/mutation++.dir/thermo/ThermoDB.cpp.o
[ 33%] Building CXX object src/CMakeFiles/mutation++.dir/transfer/MillikanWhite.cpp.o
[ 34%] Building CXX object src/CMakeFiles/mutation++.dir/transfer/OmegaCE.cpp.o
[ 35%] Building CXX object src/CMakeFiles/mutation++.dir/transfer/OmegaCElec.cpp.o
[ 38%] Building CXX object src/CMakeFiles/mutation++.dir/transfer/OmegaCV.cpp.o
[ 38%] Building CXX object src/CMakeFiles/mutation++.dir/transfer/OmegaET.cpp.o
[ 39%] Building CXX object src/CMakeFiles/mutation++.dir/transfer/OmegaI.cpp.o
[ 40%] Building CXX object src/CMakeFiles/mutation++.dir/transfer/OmegaVT.cpp.o
[ 41%] Building CXX object src/CMakeFiles/mutation++.dir/transport/CapitelliIntegrals.cpp.o
[ 43%] Building CXX object src/CMakeFiles/mutation++.dir/transport/CollisionDB.cpp.o
[ 44%] Building CXX object src/CMakeFiles/mutation++.dir/transport/CollisionGroup.cpp.o
[ 46%] Building CXX object src/CMakeFiles/mutation++.dir/transport/CollisionIntegral.cpp.o
[ 46%] Building CXX object src/CMakeFiles/mutation++.dir/transport/CollisionPair.cpp.o
[ 49%] Building CXX object src/CMakeFiles/mutation++.dir/transport/ElectronSubSystem.cpp.o
[ 49%] Building CXX object src/CMakeFiles/mutation++.dir/transport/CoulombIntegrals.cpp.o
[ 50%] Building CXX object src/CMakeFiles/mutation++.dir/transport/ExactDiffMat.cpp.o
[ 51%] Building CXX object src/CMakeFiles/mutation++.dir/transport/LangevinIntegrals.cpp.o
[ 53%] Building CXX object src/CMakeFiles/mutation++.dir/transport/RamshawDiffMat.cpp.o
[ 54%] Building CXX object src/CMakeFiles/mutation++.dir/transport/ThermalConductivityChapmannEnskog.cpp.o
[ 55%] Building CXX object src/CMakeFiles/mutation++.dir/transport/ThermalConductivityWilke.cpp.o
[ 56%] Building CXX object src/CMakeFiles/mutation++.dir/transport/Transport.cpp.o
[ 58%] Building CXX object src/CMakeFiles/mutation++.dir/transport/ViscosityChapmannEnskog.cpp.o
[ 59%] Building CXX object src/CMakeFiles/mutation++.dir/transport/ViscosityGuptaYos.cpp.o
[ 60%] Building CXX object src/CMakeFiles/mutation++.dir/transport/ViscosityWilke.cpp.o
[ 61%] Building CXX object src/CMakeFiles/mutation++.dir/utilities/StringUtils.cpp.o
[ 64%] Building CXX object src/CMakeFiles/mutation++.dir/utilities/Units.cpp.o
[ 64%] Building CXX object src/CMakeFiles/mutation++.dir/utilities/TemporaryFile.cpp.o
[ 65%] Building CXX object src/CMakeFiles/mutation++.dir/utilities/XMLite.cpp.o
[ 66%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/DiffusionVelocityCalculator.cpp.o
[ 67%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/GasFourierHeatFluxCalculator.cpp.o
[ 69%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/GasSurfaceInteraction.cpp.o
[ 70%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/GSIReactionAblation.cpp.o
[ 71%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/GSIReactionCatalysis.cpp.o
[ 74%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/GSIRateLawGammaT.cpp.o
[ 74%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/GSIRateLawGammaConst.cpp.o
[ 75%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/GSIRateLawSublimation.cpp.o
[ 76%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/GSIRateManagerPhenomenological.cpp.o
[ 79%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/GSIStoichiometryManager.cpp.o
[ 79%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/MassBlowingRateAblation.cpp.o
[ 80%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/MassBlowingRateNull.cpp.o
[ 81%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/SolidPropertiesNull.cpp.o
[ 82%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/SolidPropertiesSteadyState.cpp.o
[ 83%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/SurfaceChemistry.cpp.o
[ 85%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/SurfaceRadiation.cpp.o
[ 86%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/SurfaceBalanceSolverMass.cpp.o
[ 87%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/SurfaceBalanceSolverMassEnergy.cpp.o
[ 90%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/SurfacePropertiesNull.cpp.o
[ 90%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/SurfacePropertiesAblation.cpp.o
[ 91%] Building CXX object src/CMakeFiles/mutation++.dir/gsi/SurfaceState.cpp.o
[ 92%] Linking CXX shared library libmutation++.so
[ 92%] Built target mutation++
Scanning dependencies of target checkmix
Scanning dependencies of target bprime
Scanning dependencies of target mppequil
[ 96%] Building CXX object src/general/CMakeFiles/mppequil.dir/mppequil.cpp.o
[ 96%] Building CXX object src/general/CMakeFiles/checkmix.dir/checkmix.cpp.o
[ 96%] Building CXX object src/general/CMakeFiles/bprime.dir/bprime.cpp.o
[ 97%] Linking CXX executable bprime
[100%] Linking CXX executable mppequil
[100%] Linking CXX executable checkmix
[100%] Built target checkmix
[100%] Built target bprime
[100%] Built target mppequil
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/lib64/cmake/mutation++/mutation++Config.cmake
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/lib64/cmake/mutation++/mutation++ConfigVersion.cmake
-- Installing: /students/st_18_19/soy/Mutationpp/install/lib64/libmutation++.so
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/GlobalOptions.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/mutation++.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/Mixture.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/MixtureOptions.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/Constants.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/Errors.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/JacobianManager.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/Kinetics.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/RateLaws.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/RateLawGroup.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/RateManager.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/Reaction.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/ReactionType.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/StoichiometryManager.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/ThirdBodyManager.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/lp.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/Functors.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/Interpolators.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/NewtonSolver.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/Composition.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/MultiPhaseEquilSolver.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/ParticleRRHO.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/Species.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/SpeciesListDescriptor.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/SpeciesNameFSM.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/StateModel.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/ThermoDB.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/Thermodynamics.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/MillikanWhite.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/TransferModel.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/CollisionDB.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/CollisionGroup.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/CollisionIntegral.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/CollisionPair.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/CoulombIntegrals.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/DiffusionMatrix.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/ElectronSubSystem.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/ThermalConductivityAlgorithm.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/ViscosityAlgorithm.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/Transport.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/AutoRegistration.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/IteratorWrapper.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/LookupTable.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/ReferenceServer.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/SharedPtr.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/StringUtils.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/TemporaryFile.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/Units.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/Utilities.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/XMLite.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/DiffusionVelocityCalculator.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/GasFourierHeatFluxCalculator.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/GasSurfaceInteraction.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/GSIRateLaw.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/GSIRateManager.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/GSIReaction.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/GSIStoichiometryManager.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/MassBlowingRate.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/SolidProperties.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/SurfaceChemistry.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/SurfaceRadiation.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/include/mutation++/SurfaceState.h
-- Up-to-date: /students/st_18_19/soy/Mutationpp/install/lib64/cmake/mutation++/mutation++Targets.cmake
-- Installing: /students/st_18_19/soy/Mutationpp/install/lib64/cmake/mutation++/mutation++Targets-release.cmake
-- Installing: /students/st_18_19/soy/Mutationpp/install/bin/checkmix
-- Set runtime path of "/students/st_18_19/soy/Mutationpp/install/bin/checkmix" to ""
-- Installing: /students/st_18_19/soy/Mutationpp/install/bin/mppequil
-- Set runtime path of "/students/st_18_19/soy/Mutationpp/install/bin/mppequil" to ""
-- Installing: /students/st_18_19/soy/Mutationpp/install/bin/bprime
-- Set runtime path of "/students/st_18_19/soy/Mutationpp/install/bin/bprime" to ""
[soy@aglin21 build]$ checkmix air_11
checkmix: error while loading shared libraries: libmutation++.so: cannot open shared object file: No such file or directory
[soy@aglin21 build]$ checkmix air_11
checkmix: error while loading shared libraries: libmutation++.so: cannot open shared object file: No such file or directory
[soy@aglin21 build]$ cmake --version
cmake version 3.9.6

CMake suite maintained and supported by Kitware (kitware.com/cmake).
[soy@aglin21 build]$ gcc --version
gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-6)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[soy@aglin21 build]$ checkmix air11
checkmix: error while loading shared libraries: libmutation++.so: cannot open shared object file: No such file or directory
[soy@aglin21 build]$ mppequil
mppequil: error while loading shared libraries: libmutation++.so: cannot open shared object file: No such file or directory
[soy@aglin21 build]$ cd ..
[soy@aglin21 Mutationpp]$ checkmix air_11
checkmix: error while loading shared libraries: libmutation++.so: cannot open shared object file: No such file or directory
[soy@aglin21 Mutationpp]$ 
Hello @rubendibattista ,
This terminal includes what I have tried to load cmake 3.9.2 to solve issue, but it did not work.
Thanks

**Comment by rubendibattista** [comment]
Did you set these environment variables: https://github.com/mutationpp/Mutationpp/wiki/Installation-guide#linux

**Comment by rubendibattista** [comment]
(In particular, it looks like to me that you are on `Ubuntu`, and the the line about $LD_LIBRARY_PATH probably must be modified like this:)

`export LD_LIBRARY_PATH=$MPP_DIRECTORY/install/**lib64**:$LD_LIBRARY_PATH`

See #87 for another similar problem. We'll update the install instructions ASAP (#93)

**Comment by rubendibattista** [comment]
@soy15 Any news?

**Comment by soy15** [comment]
Thank you very much, we have managed to install @rubendibattista

**Comment by rubendibattista** [comment]
@jbscoggi You can close! :)
@soy15 Thanks for updating us :)
